#!/usr/bin/env bash
# This is a factors challenge

check_factor() {
    factors=($(factor -t -P "$1"))

    if [ ${#factors[@]} -eq 1 ]; then
        echo "$1=1*$1"
    else
        max_factor=${factors[-1]}
        second_max_factor=${factors[-2]}

        if [ ${#factors[@]} -gt 2 ]; then
            for ((i=${#factors[@]}-3; i>=0; i--)); do
                if [ $((factors[i] * second_max_factor)) -gt $((max_factor * factors[i+1])) ]; then
                    break
                fi

                second_max_factor=${factors[i]}
            done
        fi

        echo "$1=$max_factor*$second_max_factor"
    fi
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read -r number; do
        check_factor "$number"
    done < "$1"
fi
